<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251208151814 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE xuser_wallet (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(50) DEFAULT \'user\' NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, wallet_id INT NOT NULL, target_user_id INT NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2B2E09AB712520F3 ON xuser_wallet (wallet_id)');
        $this->addSql('CREATE INDEX IDX_2B2E09AB6C066AFE ON xuser_wallet (target_user_id)');
        $this->addSql('CREATE INDEX IDX_2B2E09ABB03A8386 ON xuser_wallet (created_by_id)');
        $this->addSql('CREATE INDEX IDX_2B2E09AB896DBBDE ON xuser_wallet (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_2B2E09ABC76F1F52 ON xuser_wallet (deleted_by_id)');
        $this->addSql('ALTER TABLE xuser_wallet ADD CONSTRAINT FK_2B2E09AB712520F3 FOREIGN KEY (wallet_id) REFERENCES wallet (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xuser_wallet ADD CONSTRAINT FK_2B2E09AB6C066AFE FOREIGN KEY (target_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xuser_wallet ADD CONSTRAINT FK_2B2E09ABB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xuser_wallet ADD CONSTRAINT FK_2B2E09AB896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xuser_wallet ADD CONSTRAINT FK_2B2E09ABC76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE xuser_wallet DROP CONSTRAINT FK_2B2E09AB712520F3');
        $this->addSql('ALTER TABLE xuser_wallet DROP CONSTRAINT FK_2B2E09AB6C066AFE');
        $this->addSql('ALTER TABLE xuser_wallet DROP CONSTRAINT FK_2B2E09ABB03A8386');
        $this->addSql('ALTER TABLE xuser_wallet DROP CONSTRAINT FK_2B2E09AB896DBBDE');
        $this->addSql('ALTER TABLE xuser_wallet DROP CONSTRAINT FK_2B2E09ABC76F1F52');
        $this->addSql('DROP TABLE xuser_wallet');
    }
}
